### ISSUE TITLE
Move initializeTallies() and checkMeshTemplateAndTranslations() from the constructor to OpenMCCellAverageProblem::setupProblem()

### ISSUE THREAD

**Issue by lewisgross1296** [neams-th-coe/cardinal#461]
Currently, the OpenMCCellAverageProblem constructor initializes the tallies and checks the mesh template element ordering and centroids to make sure the mesh centroids are as expected. However, to run Adaptive Mesh Refinement simulations, it would make more sense to move these functions to the `setupProblem()` function that would be called each time the mesh changes. When the mesh changes, these steps will need to be done again. As is, they currently do not. Moving these functions will fix this issue and since the constructor calls `setupProblem()`, it will still do these two important steps when the OpenMCCellAverageProblem constructor is called.

**Comment by lewisgross1296** [comment]
It looks like PR #599 may fix this issue! I noticed the PR and wanted to make sure this issue would be closed upon merge.

**Comment by aprilnovak** [comment]
Yep, it should!
