### ISSUE TITLE
git clone https://...

### ISSUE THREAD

**Issue by lewisgross1296** [neams-th-coe/cardinal#464]
In other repositories, I was able to set up automated pushing by taking advantage of the SSH Clone feature. I noticed that my Cardinal pushes were still asking for authentication, despite setting up SSH key pushing on my machine. I realized today that this is due to the fact that I cloned Cardinal via HTTPS while following [instructions in the start document](https://cardinal.cels.anl.gov/start.html)
```
git clone https://github.com/neams-th-coe/cardinal.git
```
I propose that we instead recommend
```
git clone git@github.com:neams-th-coe/cardinal.git
```
IMO it would be better to switch to SSH. This won't affect anyone who doesn't have SSH key pushing enabled, but in case anyone does try and set it up, and is confused why it doesn't work, this will save them time. To see where else this occurs, I used `grep -rI "git clone" | wc -l` from the root of my cardinal directory and got 110 hits.  I am also willing to change all these occurrences and do a little README.md on how to accomplish SSH pushing. It seems small, but it is super convenient to never have to look up your ghp key/password/etc.

**Comment by aprilnovak** [comment]
Because GitHub recommends HTTPS as the default, I think we should stick with HTTPS. It also does not require users to set up ssh keys across multiple different devices if they do development/usage in multiple places. But thank you for putting all this thought into it!
