### ISSUE TITLE
Update NekRS version

### ISSUE THREAD

**Issue by aprilnovak** [neams-th-coe/cardinal#675]
- [x] Test all tutorials
- [x] Update documentation for new syntax changes
- [x] Update VTB
- [x] Update all input files/tests using the standalone Nek case files to the new versions, if needed
- [x] Check that rendering of any empty .oudf in the documentation looks okay/delete it
- [x] Re-build on all HPC systems to check compatibility, and update the build scripts
- [x] Cherry-pick the two open PRs related to conjugate heat transfer to be sure they are now fixed
- [x] Link to the release notes in Cardinal docs
- [x] Delete empty UDF functions (but not UDF_Setup)
- [x] Update unit test makefile to hit new source files
- [x] Stress formulation is deprecated

**Comment by anshchaube** [comment]
- [ ] Replace `if (nekrs::hasElasticitySolver())` with  ` if (nekrs::hasMovingMesh() && !(nekrs::hasUserMeshSolver()))`
