### ISSUE TITLE
libMesh submodule needs update for OpenMPI

### ISSUE THREAD

**Issue by pshriwise** [neams-th-coe/cardinal#679]
I discovered this today when recompiling Cardinal after an OS upgrade. I was using GCC 12.2 and OpenMPI 4.1.4. I originally made an issue in libmesh https://github.com/libMesh/libmesh/issues/3545. It appears that the root of the problem was in the TIMPI project on which libmesh relies, but it has since been corrected.

I checked out a newer version of libmesh in a recent compilation of Cardinal and ran the nominal tests to ensure that a newer libmesh version will in fact fix this problem.

I wouldn't consider this a highly time-sensitive fix as I'm on Ubuntu 23.04 and many won't likely update to this for a while, but if it's easy enough it might be worth doing.

**Comment by aprilnovak** [comment]
Cardinal does not have libMesh as a submodule directly - our MOOSE submodule brings libMesh with it (which we don't have control of). I think this issue would make more sense on the MOOSE repo? But please let me know if I'm misunderstanding!

**Comment by pshriwise** [comment]
Whoops. Of course. It doesn't look like the fix in TIMPI has been pulled in yet. I'll ping the MOOSE team.
