### ISSUE TITLE
Potential typo in Solid and Fluid Coupling Tutorial

### ISSUE THREAD

**Issue by lewisgross1296** [neams-th-coe/cardinal#763]
I believe this [line](https://github.com/neams-th-coe/cardinal/blob/0e606acbcfccb3b8a1bd4c38523493a83e8e5f4e/tutorials/gas_assembly/solid.i#L87) from the `[Materials]` block in the Solid and Fluid Coupling tutorial may have a typo.  The relevant part of the  block looks like this 
```
[Materials]
  [graphite]
    type = HeatConductionMaterial
    thermal_conductivity_temperature_function = k_graphite
    temp = T
    block = 'graphite'
  []
  [compacts]
    type = HeatConductionMaterial
    thermal_conductivity_temperature_function = k_TRISO
    temp = T
    block = 'compacts'
  []
...
[]
```
Here are the relevant functions in this input file
```
[Functions]
  [k_graphite]
    type = ParsedFunction
    expression = '${matrix_k}'
  []
  [k_TRISO]
    type = ParsedFunction
    expression = '${kernel_fraction} * ${kernel_k} + ${buffer_fraction} * ${buffer_k} + ${fparse ipyc_fraction + opyc_fraction} * ${PyC_k} + ${sic_fraction} * ${SiC_k}'
  []
  [k_compacts]
    type = ParsedFunction
    expression = '${triso_pf} * k_TRISO + ${fparse 1.0 - triso_pf} * k_graphite'
    symbol_names = 'k_TRISO k_graphite'
    symbol_values = 'k_TRISO k_graphite'
  []
...
[]
```
There seems to be a function for computing the compact homogenized thermal conductivity, so I believe the line in the  Materials block should read
```
    thermal_conductivity_temperature_function = k_compacts
```

Feel free to close the issue if I am misinterpreting the above line. Otherwise, I can make PR to fix this.

**Comment by aprilnovak** [comment]
Good catch! Yes, that should be `k_TRISO`. Feel free to make a PR with a quick fix

**Comment by lewisgross1296** [comment]
Sorry, you mean `k_compacts`, right? (The current line reads `k_TRISO`)

**Comment by aprilnovak** [comment]
yes, sorry
