### ISSUE TITLE
openmc.i [Postprocessors] block not showing on solid fluid coupling tutorial (documentation)

### ISSUE THREAD

**Issue by lewisgross1296** [neams-th-coe/cardinal#776]
## Bug Description
I've been going through the [solid and fluid coupling tutorial](https://cardinal.cels.anl.gov/tutorials/openmc_fluid.html#) and found a small issue with how the `openmc_fluid.md` displays on the cardinal.cels.anl.gov/tutorials page. I realized that despite existing in `cardinal/tutorials/gas_assembly/openmc.i`, none of the code snippet boxes on the page display the `[Postprocessors]` block for `openmc.i`. In the input file, the `[Postprocessors]` block is situated between the `[Problem]` and `[MultiApps]` blocks ([here](https://github.com/neams-th-coe/cardinal/blob/devel/tutorials/gas_assembly/openmc.i#L198-L254)), but isn't included with either of its neighboring blocks (or the VPPs) on the docs.

## Impact
 mpact is low, since I can just port over the block from GitHub/clicking to see the full script and run. It would be nice to fix this so that new users don't get stuck.

## Fix
I think moving the `[Postprocessors]` next to the `[VectorPostprocessors]`  in `openmc.i` and making sure the code snippet on the docs shows both would be a good fix. This would involve modifying `cardinal/tutorials/gas_assembly/openmc.i` and `cardinal/doc/content/tutorials/openmc_fluid.md`, plus maybe adding a little description of the post processors to where we show the snippet. 

Can anyone confirm that this issue is also occurring for them? Fastest way to reproduce would be to go to the linked tutorial and `cmd + f` for `[Postprocessors]` and see the only hit is in `solid.i`. If so, I can make a small PR (I think this should be separate from #764)

**Comment by aprilnovak** [comment]
If you look in the markdown, the individual blocks which are highlighted on the web page will be indicated with syntax like "Start" and "end". We probably just need to tweak one of those. Please go ahead and make the necessary modification so that the Postprocessors block shows up in a place that makes sense.

**Comment by lewisgross1296** [comment]
I've thought of a few options. Wanted to run them by before implementing the PR to minimize commit history / rebasing. 

1. Move the `[Postprocessors]` block next to the `[VectorPostprocessors]` blocki in `openmc.i` and extend the code snippet that already shows `[UserObjects]` and `[VectorPostprocessors]` to now include `[Postprocessors]`. (modifies `openmc.i` and `openmc_fluid.md`)
2. Add another code snippet after the existing one containing the `[UserObjects]` and `[VectorPostprocessors]` that only shows the `[Postprocessors]` (modifies only `openmc_fluid.md` but has code out-of-order compared to the input file)
3. Extended the `[Problem]` snippet to also include the `[Postprocessors]` (a one PR but probably doesn't make as much sense in the context of the tutorial)

I think the first option makes the most sense, despite modifying more files. I don't think this would require a re-gold since moving the `[Postprocessor]` block to another spot in the input file shouldn't change the physics/results.
