### ISSUE TITLE
Clarify instructions about journal file imports

### ISSUE THREAD

**Issue by aprilnovak** [neams-th-coe/cardinal#845]
## Reason
New users to cubit may not be aware of how they need to import journal files in order to run them.

## Design
Add a one-sentence instruction for how to correctly import journal files for any Cardinal tutorials which use them.

## Impact
Better user experience.

**Comment by MendesMichael** [comment]
To run your journal file, you need to click on 'Play Journal File' (the play button on a sheet of paper icon), and then find and open your file.

**Comment by aprilnovak** [comment]
can you make this a pull request, by editing documention in `cardinal/doc`?
