### ISSUE TITLE
Explore `ignore_zeros` option for the tallies added by Cardinal

### ISSUE THREAD

**Issue by aprilnovak** [neams-th-coe/cardinal#875]
## Reason
A new capability has been added to OpenMC, `ignore_zeros` (https://github.com/openmc-dev/openmc/pull/2928), which will ignore zero tally bins when applying triggers. We should expose this option through the Cardinal interface so that we can control it via the MOOSE inputs.

## Design
Add `ignore_zeros` as an option to `OpenMCCellAverageProblem` that will get passed into OpenMC when we create tallies.

## Impact
New feature, nice for @meltawila's fusion cases where we use mesh tallies but certain scores (e.g., tritium production) necessarily have zero values in some locations.

**Comment by tjlaboss** [comment]
Feature has been renamed to `ignore_zeros` at Paul's request
