### ISSUE TITLE
Unable to run OpenMC with Python API from Cardinal

### ISSUE THREAD

**Issue by naheed23** [neams-th-coe/cardinal#909]
I recently installed Cardinal for work. Currently, I am trying to run OpenMC using Python files, but it's not working like it should. I built Cardinal with MOOSE's conda environment, which was successful. Under "Checking the Install" (https://cardinal.cels.anl.gov/with_conda.html#running), I was successfully able to run #1. However, for #2 (the one I prefer and need for the moment), when I try to execute the provided Python file, I get this error:

Traceback (most recent call last):
  File "/.../.../cardinal/tutorials/lwr_solid/make_openmc_model.py", line 19, in <module>
    import openmc
ModuleNotFoundError: No module named 'openmc'

Which, of course, indicates that my Python/Conda environment does not have OpenMC. (I have ran this code a few time times and got the same error every time). I am unsure what to do, because I don't think it would be wise to make a separate installation of OpenMC just to get the Python API to work properly, considering that #2 on checking the install implies that it should work without additional steps.

Are there some instructions I am missing to get the Python API to work properly within Cardinal? Or do I have to make separate installations (https://docs.openmc.org/en/stable/usersguide/install.html#installing-python-api)? As stated in the first sentence, this is important for my work. It's not urgent yet, but soon will be.

**Comment by nuclearkevin** [comment]
You can install the OpenMC python interface by navigating to `contrib/openmc` and running `python -m pip install .`. Afterwards, you should be able to run the generator script for the pincell.

At the moment `make_openmc_model.py` will throw an error as the tutorial hasn't been updated to account for a version change in OpenMC. I'm working on a PR to update the tutorials, but in the meantime you can change 
```python
box = openmc.rectangular_prism(pitch, pitch, boundary_type='reflective')
```
to the following:
```python
box = openmc.model.rectangular_prism(pitch, pitch, boundary_type='reflective')
```
as a quick fix.

**Comment by aprilnovak** [comment]
Thanks @nuclearkevin! And yes @naheed23, the instructions for doing this are listed just before the "Checking the Install" steps on the Cardinal documentation, here: [link](https://cardinal.cels.anl.gov/with_conda.html#:~:text=You%20may%20also%20optionally%20use%20OpenMC%27s%20Python%20API%20to%20build%20models.)

I'll update that page to make them more obvious, because another person also just asked this question.

**Comment by naheed23** [comment]
This worked! Thank you both so much for your help! I can't believe I missed those instructions on the Cardinal website.
