### ISSUE TITLE
Skinner does not seem to work if photon transport is enabled

### ISSUE THREAD

**Issue by aprilnovak** [neams-th-coe/cardinal#938]
## Bug Description
If using the mesh skinner with photon transport enabled, a seg fault occurs after reinitializing the cross sections. 

## Steps to Reproduce
We likely need to be re-initializing something related to photon transport, but I'm not sure what it is.

## Impact
Preventing photon usage with skinning.

**Comment by aprilnovak** [comment]
@pshriwise @helen-brooks , wondering if you may have any ideas on this?

**Comment by nuclearkevin** [comment]
Would `openmc::data::element_map` + `openmc::data::elements` (photon.cpp) need to be reset with the same approach as `openmc::data::nuclides` + `openmc::data::nuclides`?

**Comment by aprilnovak** [comment]
Ooh, it might be! I tried doing this, but looks like MOOSE has a `#define` which is conflicting with a similar name in OpenMC. Haven't encountered this before!

```
/home/ajnovak2/cardinal/contrib/moose/framework/build/header_symlinks/PerfGraph.h:36:24: error: expected unqualified-id before numeric constant
   36 | #define MAX_STACK_SIZE 100
```

In `openmc/include/photon.h`:

```
  // Constant data
  static constexpr int MAX_STACK_SIZE =
    7; //!< maximum possible size of atomic relaxation stack
```

**Comment by aprilnovak** [comment]
@nuclearkevin your suggestion is the correct fix, thanks!

**Comment by nuclearkevin** [comment]
Happy to help!
